name: "Tududi"
version: "0.0.3"
slug: "tududi"
description: "Tududi upstream container packaged as a Home Assistant Add-on."
url: "https://github.com/c2gl/tududi-addon"
image: "ghcr.io/c2gl/tududi-addon"
init: false
startup: services
boot: manual
arch:
  - amd64
ports:
  3002/tcp: 3002
ports_description:
  3002/tcp: "Web interface"
ingress: true
ingress_port: 3002
panel_icon: mdi:checkbox-marked-circle-outline
options:
  port: 3002
  tududi_user_email: ""
  tududi_user_password: ""
  tududi_session_secret: ""
  disable_telegram: false
  disable_scheduler: false
  upload_path: "/app/backend/uploads"
  db_file: "/app/backend/db/production.sqlite3"
schema:
  port: int
  tududi_user_email: str
  tududi_user_password: str
  tududi_session_secret: str
  disable_telegram: bool
  disable_scheduler: bool
  upload_path: str
  db_file: str
webui: "http://[HOST]:[PORT:3002]"
